### ISSUE TITLE
Parent directory creation with `.dump()`

### ISSUE THREAD

**Issue by pfackeldey** [riga/law#101]
Currently you need to always create the parent directory before you can dump data to the task output. 
e.g.:
```python
class FooBar(law.Task):

    def output(self):
        return law.LocalFileTarget("path/to/data.json")

    def run(self):
        self.output().parent.touch()
        self.output().dump(["foo", "bar"])
```
It would be very convenient if one would not have to do `self.output().parent.touch()`, at least when one uses the `.dump(...)` method.

What do you think about this @riga ?

**Comment by riga** [comment]
Yeah, I'm sometimes annoyed by this as well ;)
For local targets, this is no problem at all, but I was hesitant initially to do a "mkdir_rec" every time a remote target "copy" operation happens because this is an additional network request.
However, effectively one does the "touch()" anyway, so there might not even be a point behind the argument.
I think we can change it, but keep an option to disable automatic directory creation again.

**Comment by pfackeldey** [comment]
Alright, I thought initially only about local file targets anyway. :)

**Comment by riga** [comment]
I just made the behavior of creating parent directories consistent in the master. Would you mind giving it a spin? There is an option "create_file_dir" now which is True by default.

**Comment by pfackeldey** [comment]
works as expected! 🎉 👍

**Comment by riga** [comment]
Fixed in https://github.com/riga/law/commit/dcefd94565773485f4ee9c760937203be40c69e9.
